### PR TITLE
R spec testing

### PR DESCRIPTION
**Pull request by elasfarc**
In this project we do test the following using RSpec: 
- Board class's public methods
- Game class's methods
- Player class's methods

### CODE REVIEW

**Review by SafaErden — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️

**Hi TEAM, your project is awesome. 👐 However, we need a little fix before we can proceed. Kindly find the comments below ⤵**
##

**REQUIRED CHANGES**

- [ ] Since this is a testing project, please add testing instructions to your README.md

- [ ] A Gemfile is a file we create that is used for describing gem dependencies for Ruby programs. Your projet's Gemfile is missing which enables users to install spec gem and run tests.

##

**OPTIONAL CHANGES**

- [ ] Your README file contains typos and broken links. It would be nice to fix them to have a more professional look for your repo.

##

**SUMMARY**

 As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready💪*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Mo Al-Asfar & Ricardo Montenegro Nunez** 
Nive job following implement the changes required by the TSE :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [x] Add a screenshot of your project in the README file.
- [x] In your README file, replace "programm" with "program", and "reenter" with "re-enter".
- [x] In your README file, add a section to explain how to set up your project for anyone who wants to download and use it.
- [x] In player_spec.rb file, line 4,remove commented code
- [x] create at least two tests for each public method.
- [x] test both positive and negative scenarios. To test negative scenarios you might use "to_not_eql" or "to_not be_an".

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

- Your tests are really exceptional. Good job with namespacing your tests which brings out the descriptiveness. Carry on with this approach.

- Great job with testing for all the edge cases for all your public methods. Well done 👏 !

### However, we need to work on some changes before we can merge.

- Right now, the positive and the negative scenario tests are in the same place (in the same `it` block). It's always a good idea to separate your positive and negative tests. You will have more confidence in refactoring your code later on. And when your test fails, you will know exactly where your test is failing. That's why namespacing these is so important. You have already done a great job with it. Just a little more.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
